category: GAMES_AND_TRIVIA
defaultLocale: en
localizedSettings:
  developerEmail: goldzulu222@gmail.com
  developerName: Voicetechguy
  displayName: Rocket Ship Zulu
  fullDescription: Rocket Ship Zulu
  privacyPolicyUrl: https://docs.google.com/document/d/1JEhR3UUOoOIQ8QWRwEgL0caV4yG2lJndSm4Gv2j0-TY
  pronunciation: Rocket Ship Zulu
  sampleInvocations:
  - Talk to Rocket Ship Zulu
  shortDescription: Rocket Ship Zulu
  smallLogoImage: https://lh3.googleusercontent.com/5H9mjHOp5YwFEXB0wUBRCdzM4uwzfU9_4J2S1z9zAZw2FM0hcVzO3xi8T6asFnR0YhCOX9RjKqjq
  voice: female_1
projectId: astro-voice
usesInteractiveCanvas: true
